### ISSUE TITLE
vendor/autoload.php

### ISSUE THREAD

**Issue by FunkyCreep** [masteralb/woocommerce-bkt#1]
Hi there,

i'm trying this plugin but i'm facing an error testing it in local with xampp :

`Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\wp-test\wp-content\plugins\woocommerce-bkt\woocommerce-bkt.php on line 18

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\wp-test\wp-content\plugins\woocommerce-bkt\woocommerce-bkt.php on line 18`

**Comment by masteralb** [comment]
You must install composer packages.
Please run composer install to the plugin dir.
https://getcomposer.org/

**Comment by FunkyCreep** [comment]
Work like a charm in local. Great job mate

**Comment by masteralb** [comment]
resolved
